name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: miguelfreitas93/checkmarx-github-action@<version>
      with:
        cxServer: http://6179-31-168-164-190.ngrok.io
        cxUsername: danielge
        cxPassword: checkMARX1.
        cxTeam: \CxServer
